version: '3.4'

networks:
  dev:
    driver: bridge
services:
  inspira_api:
    depends_on:
     - "inspira_db"
    container_name: inspira-service
    ports:
      - "5009:80"
    build:
      context: ./Inspira.Api
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=User ID =inspiraAdmin;Password=Inspir@-;Server=inspira_db;Port=5432;Database=Inspira;Pooling=true;
      - ASPNETCORE_URLS=http://+:80
    networks:
      - dev
  inspira_db:
    image: postgres:latest
    container_name: inspira_db
    environment:
      - POSTGRES_USER=inspiraAdmin
      - POSTGRES_PASSWORD=Inspir@-
      - POSTGRES_DB=Inspira
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - app_data:/var/lib/postgresql/data
    networks:
      - dev
volumes:
  app_data:
